import {useEffect,useState} from 'react';
import {paginate} from './pagination';
export default function ArchiveViewer({onClose}:{onClose:()=>void}){
 const [archives,setArchives]=useState<any[]>([]),[name,setName]=useState(''),[data,setData]=useState<any>(null),[query,setQuery]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function list(){const r=await fetch('/api/archives');const d=await r.json();if(!r.ok)throw Error(d.error);setArchives(d.archives)}
 useEffect(()=>{list().catch(e=>setError(e.message))},[]);
 async function view(value:string){setBusy(true);setError('');setData(null);setSelected(null);setName(value);setPage(1);setQuery('');try{const r=await fetch('/api/archive?name='+encodeURIComponent(value));const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>512*1024*1024){setError('上传上限为 512 MB；更大的归档可放入 data/finished_order 后刷新列表。');return}setBusy(true);setError('');try{const r=await fetch('/api/archives?name='+encodeURIComponent(file.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});const d=await r.json();if(!r.ok)throw Error(d.error);await list();await view(d.name)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const filtered=(data?.rows||[]).filter((r:any)=>[r.id,r.customer,r.batch,r.owner,r.spec].join(' ').toLowerCase().includes(query.trim().toLowerCase()));const p=paginate<any>(filtered,page);
 return <div className="app-shell"><main><div className="heading"><div><h1>历史数据库查看</h1><p>只读查看归档，不会覆盖当前台账。支持完整的 RDIMM .sqlite / .db 数据库。</p></div><button className="utility-button" disabled={busy} onClick={onClose}>返回当前台账</button></div>
 <div className="archive-controls"><label>上传数据库<input type="file" accept=".sqlite,.db" disabled={busy} onChange={upload}/></label><label>已有归档<select aria-label="选择历史数据库" disabled={busy} value={name} onChange={e=>void view(e.target.value)}><option value="" disabled>选择 data/finished_order 中的数据库</option>{archives.map(a=><option key={a.name} value={a.name}>{a.name}（{(a.size/1024/1024).toFixed(1)} MB）</option>)}</select></label><button className="utility-button" disabled={busy} onClick={()=>list().catch(e=>setError(e.message))}>刷新归档列表</button></div>
 <p className="footnote">上传上限 512 MB；请使用程序生成的完整备份。上传文件保存在 data/finished_order，同名自动加序号。</p>{error&&<p className="error" role="alert">{error}</p>}{busy&&<p role="status">正在读取数据库，请稍候…</p>}
 {data&&<><p className="notice">正在查看：{name} · 共 {data.rows.length} 笔送样、{data.returns.length} 笔归还明细（历史快照）</p><label className="search">查询所有页<input aria-label="查询历史记录" placeholder="客户、批次、规格、申请人或记录编号" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><section className="records"><div className="archive-table"><table><thead><tr>{['客户 / 编号','申请人','规格 / 批次','申请数量','已归还','未归还','送出日期','约定归还','操作'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{p.items.map(r=><tr key={r.id}><td>{r.customer}<small>{r.id}</small></td><td>{r.owner}</td><td>{r.spec}<small>{r.batch}</small></td><td>{r.quantity}</td><td>{r.returned}</td><td>{r.sent?r.quantity-r.returned:'—'}</td><td>{r.sent?.slice(0,10)||'未送出'}</td><td>{r.due?.slice(0,10)||'待约定'}</td><td><button className="utility-button" onClick={()=>setSelected(r)}>查看详情</button></td></tr>)}</tbody></table></div>{!filtered.length&&<p className="empty">暂无符合条件的记录</p>}<footer className="pagination-footer"><span>共 {filtered.length} 笔 · 每页 10 条</span><nav className="pagination-controls"><button disabled={p.page===1} onClick={()=>setPage(p.page-1)}>上一页</button><span>第 {p.page} / {p.pages} 页</span><button disabled={p.page===p.pages} onClick={()=>setPage(p.page+1)}>下一页</button></nav></footer></section>
 {selected&&<section className="records archive-detail"><h2>{selected.customer} · {selected.id}</h2><div className="detail-grid">{[['申请人','owner'],['规格','spec'],['样品料号','part'],['批次','batch'],['客户平台','platform'],['申请日期','applied'],['备注','note']].map(([label,key])=><div key={key}><small>{label}</small><p>{selected[key]||'—'}</p></div>)}</div><h3>归还明细与测试报告</h3>{data.returns.filter((r:any)=>r.sample_id===selected.id).map((r:any)=><div key={r.id} className="return-report"><p>{r.returned_on} · {r.quantity} 条 · {r.note||'无备注'}</p><p>测试报告：{r.report_provided==='yes'?'已提供':r.report_provided==='no'?'未提供':'未登记'}</p>{r.report_name&&<a href={'/api/reports/'+encodeURIComponent(r.id)+'?archive='+encodeURIComponent(name)} target="_blank" rel="noopener noreferrer">下载查看：{r.report_name}</a>}</div>)}{!data.returns.some((r:any)=>r.sample_id===selected.id)&&<p>尚无归还记录</p>}</section>}</>}
 </main></div>
}
